export const dados = [
  {
    id: "WRlfwBof66s",
    tituloCanal: "Tiger Codes",
    titulo: "Aprenda JAVASCRIPT em apenas 5 MINUTOS (2023)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/WRlfwBof66s/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:05:24",
    url: "https://www.youtube.com/watch?v=WRlfwBof66s",
  },
  {
    id: "Ptbk2af68e8",
    tituloCanal: "Curso em Vídeo",
    titulo: "O que o JavaScript é capaz de fazer? - Curso JavaScript #01",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Ptbk2af68e8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:28:50",
    url: "https://www.youtube.com/watch?v=Ptbk2af68e8",
  },
  {
    id: "6YwbZbHRQ8w",
    tituloCanal: "Attekita Dev",
    titulo: "JAVASCRIPT do básico ao avançado ( Mapa de estudos / Roadmap )",
    thumbnail: {
      url: "https://i.ytimg.com/vi/6YwbZbHRQ8w/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:16:00",
    url: "https://www.youtube.com/watch?v=6YwbZbHRQ8w",
  },
  {
    id: "RvcRxEeJqi8",
    tituloCanal: "Danki Code",
    titulo: "APRENDA JAVASCRIPT EM 10 MINUTOS",
    thumbnail: {
      url: "https://i.ytimg.com/vi/RvcRxEeJqi8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:11:36",
    url: "https://www.youtube.com/watch?v=RvcRxEeJqi8",
  },
  {
    id: "lkIFF4maKMU",
    tituloCanal: "Fireship",
    titulo: "100+ JavaScript Concepts you Need to Know",
    thumbnail: {
      url: "https://i.ytimg.com/vi/lkIFF4maKMU/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:12:24",
    url: "https://www.youtube.com/watch?v=lkIFF4maKMU",
  },
  {
    id: "1c9AmeSMpUk",
    tituloCanal: "Código Fonte TV",
    titulo: "É a Hora de Falar de JavaScript!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/1c9AmeSMpUk/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:18:49",
    url: "https://www.youtube.com/watch?v=1c9AmeSMpUk",
  },
  {
    id: "YqSfq1LiGvw",
    tituloCanal: "Bonieky Lacerda",
    titulo: "Aprenda Javascript em 1 video (+ projeto prático)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/YqSfq1LiGvw/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "02:14:56",
    url: "https://www.youtube.com/watch?v=YqSfq1LiGvw",
  },
  {
    id: "TjjKcgtlsY8",
    tituloCanal: "Tech With Tim",
    titulo: "JavaScript Speed Course - JavaScript in ~75 Minutes",
    thumbnail: {
      url: "https://i.ytimg.com/vi/TjjKcgtlsY8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "01:16:06",
    url: "https://www.youtube.com/watch?v=TjjKcgtlsY8",
  },
  {
    id: "RkWNSo3fELo",
    tituloCanal: "How to Web Dev",
    titulo:
      "JavaScript Project Color Flipper Tutorial #html #css #javascript #webdevelopment #coding #web #code",
    thumbnail: {
      url: "https://i.ytimg.com/vi/RkWNSo3fELo/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:28",
    url: "https://www.youtube.com/watch?v=RkWNSo3fELo",
  },
  {
    id: "DHjqpvDnNGE",
    tituloCanal: "Fireship",
    titulo: "JavaScript in 100 Seconds",
    thumbnail: {
      url: "https://i.ytimg.com/vi/DHjqpvDnNGE/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:02:36",
    url: "https://www.youtube.com/watch?v=DHjqpvDnNGE",
  },
  {
    id: "Ri76yOpLrNg",
    tituloCanal: "Código Fonte TV",
    titulo:
      "JavaScript (A linguagem mais AMADA e/ou ODIADA 😁) // Dicionário do Programador",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Ri76yOpLrNg/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:12:02",
    url: "https://www.youtube.com/watch?v=Ri76yOpLrNg",
  },
  {
    id: "c-I5S_zTwAc",
    tituloCanal: "Aaron Jack",
    titulo: "Learn JAVASCRIPT in just 5 MINUTES (2020)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/c-I5S_zTwAc/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:05:15",
    url: "https://www.youtube.com/watch?v=c-I5S_zTwAc",
  },
  {
    id: "PkZNo7MFNFg",
    tituloCanal: "freeCodeCamp.org",
    titulo: "Learn JavaScript - Full Course for Beginners",
    thumbnail: {
      url: "https://i.ytimg.com/vi/PkZNo7MFNFg/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "03:26:43",
    url: "https://www.youtube.com/watch?v=PkZNo7MFNFg",
  },
  {
    id: "aXOChLn5ZdQ",
    tituloCanal: "Fireship",
    titulo: "JavaScript for the Haters",
    thumbnail: {
      url: "https://i.ytimg.com/vi/aXOChLn5ZdQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:02:50",
    url: "https://www.youtube.com/watch?v=aXOChLn5ZdQ",
  },
  {
    id: "W6NZfCO5SIk",
    tituloCanal: "Programming with Mosh",
    titulo:
      "JavaScript Course for Beginners – Your First Step to Web Development",
    thumbnail: {
      url: "https://i.ytimg.com/vi/W6NZfCO5SIk/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:48:17",
    url: "https://www.youtube.com/watch?v=W6NZfCO5SIk",
  },
  {
    id: "5-oiLKEWIEw",
    tituloCanal: "Devslopes",
    titulo: "Best Programming Languages #programming #coding #javascript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/5-oiLKEWIEw/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:16",
    url: "https://www.youtube.com/watch?v=5-oiLKEWIEw",
  },
  {
    id: "lfmg-EJ8gm4",
    tituloCanal: "Bro Code",
    titulo: "JavaScript Full Course for free 🌐 (2024)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/lfmg-EJ8gm4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "12:00:00",
    url: "https://www.youtube.com/watch?v=lfmg-EJ8gm4",
  },
  {
    id: "i6Oi-YtXnAU",
    tituloCanal: "Dev Aprender | Jhonatan de Souza",
    titulo: "Curso Javascript Completo 2023 [Iniciantes] + 14 Mini-Projetos",
    thumbnail: {
      url: "https://i.ytimg.com/vi/i6Oi-YtXnAU/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "04:35:32",
    url: "https://www.youtube.com/watch?v=i6Oi-YtXnAU",
  },
  {
    id: "EerdGm-ehJQ",
    tituloCanal: "SuperSimpleDev",
    titulo: "JavaScript Tutorial Full Course - Beginner to Pro (2024)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/EerdGm-ehJQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "22:15:57",
    url: "https://www.youtube.com/watch?v=EerdGm-ehJQ",
  },
  {
    id: "r9buAwVBDhA",
    tituloCanal: "Manual do Dev",
    titulo:
      "Como criar um jogo SIMPLES usando JavaScript e HTML | JavaScript para iniciantes - Tutorial",
    thumbnail: {
      url: "https://i.ytimg.com/vi/r9buAwVBDhA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:33:28",
    url: "https://www.youtube.com/watch?v=r9buAwVBDhA",
  },
  {
    id: "hHt3F5mL7Tc",
    tituloCanal: "James Q Quick",
    titulo: "JavaScript Developers TRYING to Use TypeScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/hHt3F5mL7Tc/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:15",
    url: "https://www.youtube.com/watch?v=hHt3F5mL7Tc",
  },
  {
    id: "r9I4DuGmJ2Y",
    tituloCanal: "Goodgis",
    titulo: "Making a Game in JavaScript with No Experience",
    thumbnail: {
      url: "https://i.ytimg.com/vi/r9I4DuGmJ2Y/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:05:49",
    url: "https://www.youtube.com/watch?v=r9I4DuGmJ2Y",
  },
  {
    id: "Zi-Q0t4gMC8",
    tituloCanal: "freeCodeCamp.org",
    titulo: "JavaScript Course for Beginners 2024",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Zi-Q0t4gMC8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "03:35:38",
    url: "https://www.youtube.com/watch?v=Zi-Q0t4gMC8",
  },
  {
    id: "ZRjmGq1gAEQ",
    tituloCanal: "Fireship",
    titulo: "Let’s play… Does your code suck? JavaScript Variables Edition",
    thumbnail: {
      url: "https://i.ytimg.com/vi/ZRjmGq1gAEQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:38",
    url: "https://www.youtube.com/watch?v=ZRjmGq1gAEQ",
  },
  {
    id: "hdI2bqOjy3c",
    tituloCanal: "Traversy Media",
    titulo: "JavaScript Crash Course For Beginners",
    thumbnail: {
      url: "https://i.ytimg.com/vi/hdI2bqOjy3c/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "01:40:30",
    url: "https://www.youtube.com/watch?v=hdI2bqOjy3c",
  },
  {
    id: "FtaQSdrl7YA",
    tituloCanal: "TechWorld with Nana",
    titulo: "JavaScript Tutorial for Beginners [JS Crash Course 2024]",
    thumbnail: {
      url: "https://i.ytimg.com/vi/FtaQSdrl7YA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "01:37:14",
    url: "https://www.youtube.com/watch?v=FtaQSdrl7YA",
  },
  {
    id: "I5_Gx3JNho8",
    tituloCanal: "ThePrimeagen",
    titulo: "How To Master JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/I5_Gx3JNho8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:28",
    url: "https://www.youtube.com/watch?v=I5_Gx3JNho8",
  },
  {
    id: "rIUCl6Lnp1k",
    tituloCanal: "freeCodeCamp em Português",
    titulo: "O que é JavaScript?",
    thumbnail: {
      url: "https://i.ytimg.com/vi/rIUCl6Lnp1k/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:47",
    url: "https://www.youtube.com/watch?v=rIUCl6Lnp1k",
  },
  {
    id: "QoC4RxNIs5M",
    tituloCanal: "HolaMundo",
    titulo:
      "Aprende JavaScript Ahora! curso completo desde cero para principiantes",
    thumbnail: {
      url: "https://i.ytimg.com/vi/QoC4RxNIs5M/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "03:58:56",
    url: "https://www.youtube.com/watch?v=QoC4RxNIs5M",
  },
  {
    id: "nZuWCo52wTg",
    tituloCanal: "ByteByteGo",
    titulo:
      "Top Architectural Patterns #javascript #python #web #coding #programming",
    thumbnail: {
      url: "https://i.ytimg.com/vi/nZuWCo52wTg/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:55",
    url: "https://www.youtube.com/watch?v=nZuWCo52wTg",
  },
  {
    id: "uyw0bm0r5uA",
    tituloCanal: "RoadsideCoder",
    titulo:
      "Spread and Rest Operators in JavaScript #javascript #DSA #javascriptinterview",
    thumbnail: {
      url: "https://i.ytimg.com/vi/uyw0bm0r5uA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:57",
    url: "https://www.youtube.com/watch?v=uyw0bm0r5uA",
  },
  {
    id: "eiC58R16hb8",
    tituloCanal: "Lydia Hallie",
    titulo: "JavaScript Visualized - Event Loop, Web APIs, (Micro)task Queue",
    thumbnail: {
      url: "https://i.ytimg.com/vi/eiC58R16hb8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:12:35",
    url: "https://www.youtube.com/watch?v=eiC58R16hb8",
  },
  {
    id: "y2OHIr_CZ4s",
    tituloCanal: "Learning Axis",
    titulo: "Pikachu | HTML CSS JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/y2OHIr_CZ4s/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=y2OHIr_CZ4s",
  },
  {
    id: "zO6CHvTErxE",
    tituloCanal: "Sam Meech-Ward",
    titulo:
      "The best thing you can do with JavaScript #javascript #programming",
    thumbnail: {
      url: "https://i.ytimg.com/vi/zO6CHvTErxE/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:37",
    url: "https://www.youtube.com/watch?v=zO6CHvTErxE",
  },
  {
    id: "b4TpO9pYpqk",
    tituloCanal: "ByteByteGo",
    titulo:
      "Top 5 API Performance Tips #javascript #python #web #coding #programming",
    thumbnail: {
      url: "https://i.ytimg.com/vi/b4TpO9pYpqk/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:58",
    url: "https://www.youtube.com/watch?v=b4TpO9pYpqk",
  },
  {
    id: "L6btUQ8mDZo",
    tituloCanal: "Web Dev Simplified",
    titulo: "I Cannot Believe JavaScript Finally Added This New Array Method",
    thumbnail: {
      url: "https://i.ytimg.com/vi/L6btUQ8mDZo/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:57",
    url: "https://www.youtube.com/watch?v=L6btUQ8mDZo",
  },
  {
    id: "n4iBQzjWxb0",
    tituloCanal: "Victor Lima - Ciência da Computação",
    titulo:
      "Javascript É Uma Linguagem Engraçada 🤡 #shorts #javascript #programador #python #php",
    thumbnail: {
      url: "https://i.ytimg.com/vi/n4iBQzjWxb0/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:17",
    url: "https://www.youtube.com/watch?v=n4iBQzjWxb0",
  },
  {
    id: "5lvXwWJU17c",
    tituloCanal: "Coding with Lewis",
    titulo:
      "Build desktop apps with JavaScript easily 👩‍💻 #technology #programming #software #code #javascript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/5lvXwWJU17c/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:39",
    url: "https://www.youtube.com/watch?v=5lvXwWJU17c",
  },
  {
    id: "yeOdtJ0IJqs",
    tituloCanal: "HighDev4",
    titulo:
      "Porque odeiam java #python #desenvolvedores #javascript #desenvolvedor #programação #coding #progra",
    thumbnail: {
      url: "https://i.ytimg.com/vi/yeOdtJ0IJqs/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:54",
    url: "https://www.youtube.com/watch?v=yeOdtJ0IJqs",
  },
  {
    id: "ivdTnPl1ND0",
    tituloCanal: "freeCodeCamp Español",
    titulo: "Aprende JavaScript - Curso Completo desde Cero",
    thumbnail: {
      url: "https://i.ytimg.com/vi/ivdTnPl1ND0/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "09:15:21",
    url: "https://www.youtube.com/watch?v=ivdTnPl1ND0",
  },
  {
    id: "RPyA7buPBas",
    tituloCanal: "Alex Ziskind",
    titulo: "JavaScript vs Python for web development",
    thumbnail: {
      url: "https://i.ytimg.com/vi/RPyA7buPBas/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:59",
    url: "https://www.youtube.com/watch?v=RPyA7buPBas",
  },
  {
    id: "9emXNzqCKyg",
    tituloCanal: "Fireship",
    titulo: "The JavaScript Survival Guide",
    thumbnail: {
      url: "https://i.ytimg.com/vi/9emXNzqCKyg/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:14:47",
    url: "https://www.youtube.com/watch?v=9emXNzqCKyg",
  },
  {
    id: "-rtxfuRTVT4",
    tituloCanal: "Travis Media",
    titulo: "Just Learn JavaScript!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/-rtxfuRTVT4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:48",
    url: "https://www.youtube.com/watch?v=-rtxfuRTVT4",
  },
  {
    id: "PFmuCDHHpwk",
    tituloCanal: "Programming with Mosh",
    titulo:
      "Object-oriented Programming in JavaScript: Made Super Simple | Mosh",
    thumbnail: {
      url: "https://i.ytimg.com/vi/PFmuCDHHpwk/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "01:02:49",
    url: "https://www.youtube.com/watch?v=PFmuCDHHpwk",
  },
  {
    id: "jS4aFq5-91M",
    tituloCanal: "freeCodeCamp.org",
    titulo: "JavaScript Programming - Full Course",
    thumbnail: {
      url: "https://i.ytimg.com/vi/jS4aFq5-91M/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "07:44:20",
    url: "https://www.youtube.com/watch?v=jS4aFq5-91M",
  },
  {
    id: "xwKbtUP87Dk",
    tituloCanal: "Topknot Clare",
    titulo: "JavaScript Basics in 10 Minutes",
    thumbnail: {
      url: "https://i.ytimg.com/vi/xwKbtUP87Dk/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:11:49",
    url: "https://www.youtube.com/watch?v=xwKbtUP87Dk",
  },
  {
    id: "Ihy0QziLDf0",
    tituloCanal: "Bro Code",
    titulo: "JavaScript tutorial for beginners 🌐",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Ihy0QziLDf0/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:12:03",
    url: "https://www.youtube.com/watch?v=Ihy0QziLDf0",
  },
  {
    id: "jo6U429l3JM",
    tituloCanal: "ByteByteGo",
    titulo: "1 TRILLION messages #javascript #python #web #coding #programming",
    thumbnail: {
      url: "https://i.ytimg.com/vi/jo6U429l3JM/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=jo6U429l3JM",
  },
  {
    id: "KQ712CebFDM",
    tituloCanal: "Conner Ardman",
    titulo: "Solving JavaScript's Most NOTORIOUS Interview Question",
    thumbnail: {
      url: "https://i.ytimg.com/vi/KQ712CebFDM/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:57",
    url: "https://www.youtube.com/watch?v=KQ712CebFDM",
  },
  {
    id: "ancXNJ44Y30",
    tituloCanal: "NewForm with Brandon Groce",
    titulo:
      "Toggle Button Without HTML, CSS Or Javascript (Full Tutorial in Description)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/ancXNJ44Y30/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:11",
    url: "https://www.youtube.com/watch?v=ancXNJ44Y30",
  },
  {
    id: "aWfYxg-Ypm4",
    tituloCanal: "Programmers are also human",
    titulo: "Interview with Senior JS Developer 2024 [NEW]",
    thumbnail: {
      url: "https://i.ytimg.com/vi/aWfYxg-Ypm4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:06:45",
    url: "https://www.youtube.com/watch?v=aWfYxg-Ypm4",
  },
  {
    id: "fGQckyRlAOY",
    tituloCanal: "Apna College",
    titulo: "JavaScript Coding Interview Question | @ApnaCollegeOfficial",
    thumbnail: {
      url: "https://i.ytimg.com/vi/fGQckyRlAOY/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:53",
    url: "https://www.youtube.com/watch?v=fGQckyRlAOY",
  },
  {
    id: "quJzdnXuNDc",
    tituloCanal: "Andy Sterkowitz",
    titulo: "How to Learn Javascript in 2023 (From ZERO)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/quJzdnXuNDc/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:08:04",
    url: "https://www.youtube.com/watch?v=quJzdnXuNDc",
  },
  {
    id: "uaWYRL0g1iw",
    tituloCanal: "Internet Made Coder",
    titulo: "How to MASTER Javascript FAST in 2023",
    thumbnail: {
      url: "https://i.ytimg.com/vi/uaWYRL0g1iw/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:12:49",
    url: "https://www.youtube.com/watch?v=uaWYRL0g1iw",
  },
  {
    id: "aXcuz6fn8_w",
    tituloCanal: "Fireship",
    titulo: "the untold history of web development",
    thumbnail: {
      url: "https://i.ytimg.com/vi/aXcuz6fn8_w/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:54",
    url: "https://www.youtube.com/watch?v=aXcuz6fn8_w",
  },
  {
    id: "upDLs1sn7g4",
    tituloCanal: "Programming with Mosh",
    titulo: "What is JavaScript?",
    thumbnail: {
      url: "https://i.ytimg.com/vi/upDLs1sn7g4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:05:12",
    url: "https://www.youtube.com/watch?v=upDLs1sn7g4",
  },
  {
    id: "E3XxeE7NF30",
    tituloCanal: "Tech With Tim",
    titulo: "Learn JavaScript With This ONE Project!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/E3XxeE7NF30/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "01:10:26",
    url: "https://www.youtube.com/watch?v=E3XxeE7NF30",
  },
  {
    id: "x8lcdDbKZto",
    tituloCanal: "ByteByteGo",
    titulo:
      "Why is Redis so FAST #javascript #python #web #coding #programming",
    thumbnail: {
      url: "https://i.ytimg.com/vi/x8lcdDbKZto/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:48",
    url: "https://www.youtube.com/watch?v=x8lcdDbKZto",
  },
  {
    id: "-oTdhdhZFrw",
    tituloCanal: "Alberta Tech",
    titulo: "Why not just re-write the whole app in javascript? #corporate",
    thumbnail: {
      url: "https://i.ytimg.com/vi/-oTdhdhZFrw/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:22",
    url: "https://www.youtube.com/watch?v=-oTdhdhZFrw",
  },
  {
    id: "QnbspJRf7wc",
    tituloCanal: "AccioJob",
    titulo:
      "#shorts #programming #coding #css #html #javascript #ui #ux #design #programmers",
    thumbnail: {
      url: "https://i.ytimg.com/vi/QnbspJRf7wc/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:25",
    url: "https://www.youtube.com/watch?v=QnbspJRf7wc",
  },
  {
    id: "Yg1Wf_rFG7Q",
    tituloCanal: "ColorCode",
    titulo: "JavaScript Promises 👨🏻‍💻in 1 Minute #shorts",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Yg1Wf_rFG7Q/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=Yg1Wf_rFG7Q",
  },
  {
    id: "hQUjpbb75eY",
    tituloCanal: "ByteByteGo",
    titulo:
      "REST APIs Explained in 30 secs #javascript #python #web #coding #programming",
    thumbnail: {
      url: "https://i.ytimg.com/vi/hQUjpbb75eY/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:32",
    url: "https://www.youtube.com/watch?v=hQUjpbb75eY",
  },
  {
    id: "bORjV6Lp0GM",
    tituloCanal: "Sam Meech-Ward",
    titulo: "JavaScript is object oriented #javascript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/bORjV6Lp0GM/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:58",
    url: "https://www.youtube.com/watch?v=bORjV6Lp0GM",
  },
  {
    id: "wYaDZU6RGa0",
    tituloCanal: "Airbyte",
    titulo: "How to Learn JavaScript Easily and FOR FREE! 🔥",
    thumbnail: {
      url: "https://i.ytimg.com/vi/wYaDZU6RGa0/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:54",
    url: "https://www.youtube.com/watch?v=wYaDZU6RGa0",
  },
  {
    id: "BI1o2H9z9fo",
    tituloCanal: "Traversy Media",
    titulo: "Modern JavaScript From The Beginning | First 12 Hours",
    thumbnail: {
      url: "https://i.ytimg.com/vi/BI1o2H9z9fo/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "11:54:00",
    url: "https://www.youtube.com/watch?v=BI1o2H9z9fo",
  },
  {
    id: "maV3r9KJY4o",
    tituloCanal: "Creative Tim Tutorials",
    titulo: "What is JavaScript and what is it used for?",
    thumbnail: {
      url: "https://i.ytimg.com/vi/maV3r9KJY4o/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:53",
    url: "https://www.youtube.com/watch?v=maV3r9KJY4o",
  },
  {
    id: "qikxEIxsXco",
    tituloCanal: "Akshay Saini",
    titulo: "Closures in JS 🔥 | Namaste JavaScript Episode 10",
    thumbnail: {
      url: "https://i.ytimg.com/vi/qikxEIxsXco/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:22:44",
    url: "https://www.youtube.com/watch?v=qikxEIxsXco",
  },
  {
    id: "TWaLeC-kmyU",
    tituloCanal: "ByteByteGo",
    titulo:
      "Stack Overflow's Shocking Architecture #javascript #python #web #coding #programming",
    thumbnail: {
      url: "https://i.ytimg.com/vi/TWaLeC-kmyU/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:55",
    url: "https://www.youtube.com/watch?v=TWaLeC-kmyU",
  },
  {
    id: "pUB_nqXFfy8",
    tituloCanal: "DIVINE CLASSES AN INSTITUTION Of EDUCATION.",
    titulo:
      "Junior Vs Senior Frontend developer.#programming #javascript #html #css#webdevelopment #html5#coding",
    thumbnail: {
      url: "https://i.ytimg.com/vi/pUB_nqXFfy8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:22",
    url: "https://www.youtube.com/watch?v=pUB_nqXFfy8",
  },
  {
    id: "Zmx0Ou5TNJs",
    tituloCanal: "Flutter Mapp",
    titulo: 'Nesting "If Statements" Is Bad. Do This Instead.',
    thumbnail: {
      url: "https://i.ytimg.com/vi/Zmx0Ou5TNJs/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=Zmx0Ou5TNJs",
  },
  {
    id: "IC5vBKc21X8",
    tituloCanal: "Telusko",
    titulo: "JavaScript Programming Tutorial for Beginners",
    thumbnail: {
      url: "https://i.ytimg.com/vi/IC5vBKc21X8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "05:26:05",
    url: "https://www.youtube.com/watch?v=IC5vBKc21X8",
  },
  {
    id: "wPLyH1lp0bM",
    tituloCanal: "Coding with Lewis",
    titulo:
      "This Open Source Dev Tool is AMAZING 👩‍💻 #software #programming #technology #code #javascript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/wPLyH1lp0bM/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=wPLyH1lp0bM",
  },
  {
    id: "37SwqREHRGI",
    tituloCanal: "Rocketseat",
    titulo: "TUDO que você deve estudar de JavaScript antes do React",
    thumbnail: {
      url: "https://i.ytimg.com/vi/37SwqREHRGI/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "01:25:24",
    url: "https://www.youtube.com/watch?v=37SwqREHRGI",
  },
  {
    id: "L8lSoNm6xPU",
    tituloCanal: "Apna College",
    titulo: "A Brief History of JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/L8lSoNm6xPU/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:53",
    url: "https://www.youtube.com/watch?v=L8lSoNm6xPU",
  },
  {
    id: "Fnlnw8uY6jo",
    tituloCanal: "Akshay Saini",
    titulo:
      "Hoisting in JavaScript 🔥(variables & functions) | Namaste JavaScript Ep. 3",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Fnlnw8uY6jo/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:19:11",
    url: "https://www.youtube.com/watch?v=Fnlnw8uY6jo",
  },
  {
    id: "jNgppRzIaMc",
    tituloCanal: "Chai aur Code",
    titulo: "How to master javascript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/jNgppRzIaMc/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:58",
    url: "https://www.youtube.com/watch?v=jNgppRzIaMc",
  },
  {
    id: "_pWA4rbzvIg",
    tituloCanal: "Beyond Fireship",
    titulo:
      "JavaScript performance is weird... Write scientifically faster code with benchmarking",
    thumbnail: {
      url: "https://i.ytimg.com/vi/_pWA4rbzvIg/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:08:20",
    url: "https://www.youtube.com/watch?v=_pWA4rbzvIg",
  },
  {
    id: "Oe4eSeUY2xo",
    tituloCanal: "Conner Ardman",
    titulo: "Stop Making This Async/Await JavaScript Mistake!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Oe4eSeUY2xo/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=Oe4eSeUY2xo",
  },
  {
    id: "cMt9U6kCWsM",
    tituloCanal: "Kevin Powell",
    titulo: "The different types of JavaScript functions explained",
    thumbnail: {
      url: "https://i.ytimg.com/vi/cMt9U6kCWsM/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:14:47",
    url: "https://www.youtube.com/watch?v=cMt9U6kCWsM",
  },
  {
    id: "bYIhwrHHo3w",
    tituloCanal: "Code With Nomi",
    titulo:
      "Fast Food App in React Native 🔥 #shorts #reactnative #expo #reactjs #app #ui",
    thumbnail: {
      url: "https://i.ytimg.com/vi/bYIhwrHHo3w/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:24",
    url: "https://www.youtube.com/watch?v=bYIhwrHHo3w",
  },
  {
    id: "r3YUoVRraJ4",
    tituloCanal: "Coding with Lewis",
    titulo:
      "Functional Programming in 60 Seconds 👩‍💻 #tech #programming #software #python #javascript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/r3YUoVRraJ4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=r3YUoVRraJ4",
  },
  {
    id: "CxgOKJh4zWE",
    tituloCanal: "Bogdan Stashchuk",
    titulo: "JavaScript - Полный Курс JavaScript Для Начинающих [11 ЧАСОВ]",
    thumbnail: {
      url: "https://i.ytimg.com/vi/CxgOKJh4zWE/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "10:55:34",
    url: "https://www.youtube.com/watch?v=CxgOKJh4zWE",
  },
  {
    id: "nF13693R0sU",
    tituloCanal: "Creative Tim Tutorials",
    titulo: "Best sites to learn JavaScript for free",
    thumbnail: {
      url: "https://i.ytimg.com/vi/nF13693R0sU/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:15",
    url: "https://www.youtube.com/watch?v=nF13693R0sU",
  },
  {
    id: "8GTaO9XhA5M",
    tituloCanal: "Programador X",
    titulo: "Aprende JavaScript en 10 minutos 👨‍💻",
    thumbnail: {
      url: "https://i.ytimg.com/vi/8GTaO9XhA5M/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:11:43",
    url: "https://www.youtube.com/watch?v=8GTaO9XhA5M",
  },
  {
    id: "NO5kUNxGIu0",
    tituloCanal: "Bro Code",
    titulo: "The JavaScript DOM explained in 5 minutes! 🌳",
    thumbnail: {
      url: "https://i.ytimg.com/vi/NO5kUNxGIu0/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:05:01",
    url: "https://www.youtube.com/watch?v=NO5kUNxGIu0",
  },
  {
    id: "t5ZDRmQtDBA",
    tituloCanal: "Neeraj Walia",
    titulo:
      "Dont worry just dont be a framework user......#coding #programming #devin #ai #javascript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/t5ZDRmQtDBA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:59",
    url: "https://www.youtube.com/watch?v=t5ZDRmQtDBA",
  },
  {
    id: "waowIDofj0M",
    tituloCanal: "ezsNippet",
    titulo:
      "Be smart . #javascript #programming #coding ##interview #job #smart",
    thumbnail: {
      url: "https://i.ytimg.com/vi/waowIDofj0M/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:46",
    url: "https://www.youtube.com/watch?v=waowIDofj0M",
  },
  {
    id: "IfrJfGowmj0",
    tituloCanal: "Tiff In Tech",
    titulo:
      "What is the difference between JavaScript and TypeScript ?! #tech #coding #stem",
    thumbnail: {
      url: "https://i.ytimg.com/vi/IfrJfGowmj0/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:59",
    url: "https://www.youtube.com/watch?v=IfrJfGowmj0",
  },
  {
    id: "5fb2aPlgoys",
    tituloCanal: "freeCodeCamp.org",
    titulo: "JavaScript DOM Manipulation – Full Course for Beginners",
    thumbnail: {
      url: "https://i.ytimg.com/vi/5fb2aPlgoys/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "02:41:21",
    url: "https://www.youtube.com/watch?v=5fb2aPlgoys",
  },
  {
    id: "QVrrqgDhhu4",
    tituloCanal: "Filipe Deschamps",
    titulo:
      "Eu quero saber se você consegue responder essas 3 perguntas de JavaScript!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/QVrrqgDhhu4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:17:49",
    url: "https://www.youtube.com/watch?v=QVrrqgDhhu4",
  },
  {
    id: "4PZeIwXx1hc",
    tituloCanal: "Web Dev Simplified",
    titulo: "Maps Are A Game Changer For JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/4PZeIwXx1hc/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=4PZeIwXx1hc",
  },
  {
    id: "m55PTVUrlnA",
    tituloCanal: "PedroTech",
    titulo: "All The JavaScript You Need To Know For React",
    thumbnail: {
      url: "https://i.ytimg.com/vi/m55PTVUrlnA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:28:00",
    url: "https://www.youtube.com/watch?v=m55PTVUrlnA",
  },
  {
    id: "a00NRSFgHsY",
    tituloCanal: "James Q Quick",
    titulo: "5 JavaScript Concepts You HAVE TO KNOW",
    thumbnail: {
      url: "https://i.ytimg.com/vi/a00NRSFgHsY/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:09:38",
    url: "https://www.youtube.com/watch?v=a00NRSFgHsY",
  },
  {
    id: "t0ONFCY6NWI",
    tituloCanal: "ByteByteGo",
    titulo: "Why gRPC is Popular #javascript #python #web #coding #programming",
    thumbnail: {
      url: "https://i.ytimg.com/vi/t0ONFCY6NWI/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:59",
    url: "https://www.youtube.com/watch?v=t0ONFCY6NWI",
  },
  {
    id: "ANCm3oG7htM",
    tituloCanal: "Fireship",
    titulo: "10 JavaScript changes you missed in 2023",
    thumbnail: {
      url: "https://i.ytimg.com/vi/ANCm3oG7htM/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:05:56",
    url: "https://www.youtube.com/watch?v=ANCm3oG7htM",
  },
  {
    id: "3iWoNJbGO2U",
    tituloCanal: "ThePrimeTime",
    titulo: "Classic JavaScript L",
    thumbnail: {
      url: "https://i.ytimg.com/vi/3iWoNJbGO2U/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:30",
    url: "https://www.youtube.com/watch?v=3iWoNJbGO2U",
  },
  {
    id: "Bv_5Zv5c-Ts",
    tituloCanal: "Tony Alicea",
    titulo: "JavaScript: Understanding the Weird Parts - The First 3.5 Hours",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Bv_5Zv5c-Ts/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "03:32:50",
    url: "https://www.youtube.com/watch?v=Bv_5Zv5c-Ts",
  },
  {
    id: "Aabh97P31FA",
    tituloCanal: "LearnVue",
    titulo: "vue is the best web js framework, change my mind",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Aabh97P31FA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:29",
    url: "https://www.youtube.com/watch?v=Aabh97P31FA",
  },
  {
    id: "FuCiNVP88pc",
    tituloCanal: "Absolute",
    titulo: "JavaScript en 5 Minutos o más!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/FuCiNVP88pc/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:08:14",
    url: "https://www.youtube.com/watch?v=FuCiNVP88pc",
  },
  {
    id: "rUTKomc2gG8",
    tituloCanal: "Curso em Vídeo",
    titulo: "JavaScript: como chegamos até aqui? - Curso JavaScript #02",
    thumbnail: {
      url: "https://i.ytimg.com/vi/rUTKomc2gG8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:24:47",
    url: "https://www.youtube.com/watch?v=rUTKomc2gG8",
  },
  {
    id: "LO5eTH4Pe8E",
    tituloCanal: "Simplilearn",
    titulo:
      "JavaScript In 10 Minutes | JavaScript Tutorial For Beginners | Learn JavaScript | Simplilearn",
    thumbnail: {
      url: "https://i.ytimg.com/vi/LO5eTH4Pe8E/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:11:54",
    url: "https://www.youtube.com/watch?v=LO5eTH4Pe8E",
  },
  {
    id: "I5X3n0M5FLQ",
    tituloCanal: "Coding for All ",
    titulo:
      "5 Youtube channels to Master Javascript + React + NodeJs #javascript #coding",
    thumbnail: {
      url: "https://i.ytimg.com/vi/I5X3n0M5FLQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:59",
    url: "https://www.youtube.com/watch?v=I5X3n0M5FLQ",
  },
  {
    id: "0rZywO6jdU4",
    tituloCanal: "JetBrains",
    titulo: "You Don’t Need JavaScript for That, by Kevin Powell",
    thumbnail: {
      url: "https://i.ytimg.com/vi/0rZywO6jdU4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:39:26",
    url: "https://www.youtube.com/watch?v=0rZywO6jdU4",
  },
  {
    id: "s9wW2PpJsmQ",
    tituloCanal: "Programming with Mosh",
    titulo: "JavaScript Loops",
    thumbnail: {
      url: "https://i.ytimg.com/vi/s9wW2PpJsmQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:06:49",
    url: "https://www.youtube.com/watch?v=s9wW2PpJsmQ",
  },
  {
    id: "6r3FXekOUSk",
    tituloCanal: "Neeraj Walia",
    titulo:
      "Delete in js                            #coding #programming #js #javascript #delete",
    thumbnail: {
      url: "https://i.ytimg.com/vi/6r3FXekOUSk/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:55",
    url: "https://www.youtube.com/watch?v=6r3FXekOUSk",
  },
  {
    id: "Ew7KG2j8eII",
    tituloCanal: "From Scratch - Le développement Web de zéro",
    titulo:
      "[Cours / Tuto débutant] Apprendre Javascript de A à Z – Les bases (1/6)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Ew7KG2j8eII/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "01:16:49",
    url: "https://www.youtube.com/watch?v=Ew7KG2j8eII",
  },
  {
    id: "vyqbNFMDRGQ",
    tituloCanal: "Chris Courses",
    titulo: "JavaScript Fighting Game Tutorial with HTML Canvas",
    thumbnail: {
      url: "https://i.ytimg.com/vi/vyqbNFMDRGQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "03:56:20",
    url: "https://www.youtube.com/watch?v=vyqbNFMDRGQ",
  },
  {
    id: "jJ9Uk8ibWcA",
    tituloCanal: "RoadsideCoder",
    titulo:
      "Function Expressions in Javascript 🔥 #javascript #javascriptinterview",
    thumbnail: {
      url: "https://i.ytimg.com/vi/jJ9Uk8ibWcA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=jJ9Uk8ibWcA",
  },
  {
    id: "8dWL3wF_OMw",
    tituloCanal: "Bro Code",
    titulo: "JavaScript Full Course for free 🌐",
    thumbnail: {
      url: "https://i.ytimg.com/vi/8dWL3wF_OMw/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "08:00:00",
    url: "https://www.youtube.com/watch?v=8dWL3wF_OMw",
  },
  {
    id: "iILFBGm_I9M",
    tituloCanal: "AsmrProg",
    titulo: "ASMR Programming - Weather App With Javascript - No Talking",
    thumbnail: {
      url: "https://i.ytimg.com/vi/iILFBGm_I9M/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:20:30",
    url: "https://www.youtube.com/watch?v=iILFBGm_I9M",
  },
  {
    id: "Gl_9leTxriU",
    tituloCanal: "Akshay Saini",
    titulo: "Best way to learn JavaScript for FREE #javascript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Gl_9leTxriU/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:08",
    url: "https://www.youtube.com/watch?v=Gl_9leTxriU",
  },
  {
    id: "rVDBxCgU5oA",
    tituloCanal: "Clever Programmer",
    titulo: "When a Javascript developer discovers React for the first time...",
    thumbnail: {
      url: "https://i.ytimg.com/vi/rVDBxCgU5oA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:08",
    url: "https://www.youtube.com/watch?v=rVDBxCgU5oA",
  },
  {
    id: "zJSY8tbf_ys",
    tituloCanal: "freeCodeCamp.org",
    titulo: "Frontend Web Development Bootcamp Course (JavaScript, HTML, CSS)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/zJSY8tbf_ys/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "21:14:42",
    url: "https://www.youtube.com/watch?v=zJSY8tbf_ys",
  },
  {
    id: "qwJwNWKEUkA",
    tituloCanal: "Bitfumes",
    titulo: "JavaScript vs TypeScript #javascript #coding",
    thumbnail: {
      url: "https://i.ytimg.com/vi/qwJwNWKEUkA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:59",
    url: "https://www.youtube.com/watch?v=qwJwNWKEUkA",
  },
  {
    id: "SbfgioL6VvA",
    tituloCanal: "Sam Meech-Ward",
    titulo:
      "How To Start Writing Unit Tests #programming #javascript #webdevelopment",
    thumbnail: {
      url: "https://i.ytimg.com/vi/SbfgioL6VvA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=SbfgioL6VvA",
  },
  {
    id: "NiQd9hZbuVo",
    tituloCanal: "Stefan Mischook",
    titulo: "Should you Learn JavaScript in 2024?",
    thumbnail: {
      url: "https://i.ytimg.com/vi/NiQd9hZbuVo/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:59",
    url: "https://www.youtube.com/watch?v=NiQd9hZbuVo",
  },
  {
    id: "qKC0AeHxVB4",
    tituloCanal: "Felipe Rocha • Full Stack Club",
    titulo:
      "Vem ver como criar funções melhores no #javascript com essa simples técnica!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/qKC0AeHxVB4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:52",
    url: "https://www.youtube.com/watch?v=qKC0AeHxVB4",
  },
  {
    id: "tj5VW2xJsqU",
    tituloCanal: "ThePrimeTime",
    titulo: "Javascript To Typescript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/tj5VW2xJsqU/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:59",
    url: "https://www.youtube.com/watch?v=tj5VW2xJsqU",
  },
  {
    id: "31AcXasOg08",
    tituloCanal: "Treehouse",
    titulo: "What is Full Stack JavaScript Development?",
    thumbnail: {
      url: "https://i.ytimg.com/vi/31AcXasOg08/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=31AcXasOg08",
  },
  {
    id: "z1a0eHWn5ds",
    tituloCanal: "Carlos Azaustre - Aprende JavaScript",
    titulo: "Cómo dominar el DOM en JavaScript en 30 minutos 🌳 2024",
    thumbnail: {
      url: "https://i.ytimg.com/vi/z1a0eHWn5ds/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:31:29",
    url: "https://www.youtube.com/watch?v=z1a0eHWn5ds",
  },
  {
    id: "AUTO7ALJk2U",
    tituloCanal: "Interview Happy",
    titulo: "Top 100 JavaScript Interview Questions and Answers",
    thumbnail: {
      url: "https://i.ytimg.com/vi/AUTO7ALJk2U/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "03:00:42",
    url: "https://www.youtube.com/watch?v=AUTO7ALJk2U",
  },
  {
    id: "B7wHpNUUT4Y",
    tituloCanal: "Apna College",
    titulo: "Javascript Introduction | Lecture 1 | Web Development Course",
    thumbnail: {
      url: "https://i.ytimg.com/vi/B7wHpNUUT4Y/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:07:48",
    url: "https://www.youtube.com/watch?v=B7wHpNUUT4Y",
  },
  {
    id: "oYhNLfh7oto",
    tituloCanal: "Cod3r Cursos",
    titulo:
      "O Essencial de JavaScript - Fundamentos Essenciais para o Desenvolvimento de Aplicações",
    thumbnail: {
      url: "https://i.ytimg.com/vi/oYhNLfh7oto/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "03:20:24",
    url: "https://www.youtube.com/watch?v=oYhNLfh7oto",
  },
  {
    id: "o1IaduQICO0",
    tituloCanal: "edureka!",
    titulo:
      "JavaScript Full Course | JavaScript Tutorial For Beginners | JavaScript Training | Edureka",
    thumbnail: {
      url: "https://i.ytimg.com/vi/o1IaduQICO0/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "03:32:35",
    url: "https://www.youtube.com/watch?v=o1IaduQICO0",
  },
  {
    id: "lI1ae4REbFM",
    tituloCanal: "Clever Programmer",
    titulo:
      "JavaScript Tutorial for Beginners - Full Course in 12 Hours (2022)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/lI1ae4REbFM/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "12:21:23",
    url: "https://www.youtube.com/watch?v=lI1ae4REbFM",
  },
  {
    id: "KORSNqaZWnM",
    tituloCanal: "Sam Meech-Ward",
    titulo: "Javascript is Bananas #javascript #programming",
    thumbnail: {
      url: "https://i.ytimg.com/vi/KORSNqaZWnM/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:57",
    url: "https://www.youtube.com/watch?v=KORSNqaZWnM",
  },
  {
    id: "v3Ho7QVaTXM",
    tituloCanal: "Melvynx • Apprendre à coder",
    titulo: "Apprendre JavaScript en juste 5 MINUTES (2024)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/v3Ho7QVaTXM/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:06:03",
    url: "https://www.youtube.com/watch?v=v3Ho7QVaTXM",
  },
  {
    id: "VlPiVmYuoqw",
    tituloCanal: "Apna College",
    titulo:
      "JavaScript Tutorial (2024) for Beginners to Pro (with Notes, Projects & Practice Questions)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/VlPiVmYuoqw/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "11:47:14",
    url: "https://www.youtube.com/watch?v=VlPiVmYuoqw",
  },
  {
    id: "eWLDAAMsD-c",
    tituloCanal: "Programmieren lernen",
    titulo:
      "JavaScript Tutorial für Anfänger: Lerne JavaScript in 90 Minuten (deutsch)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/eWLDAAMsD-c/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "01:30:51",
    url: "https://www.youtube.com/watch?v=eWLDAAMsD-c",
  },
  {
    id: "N8Xt5rP_DUo",
    tituloCanal: "Sergie Code",
    titulo:
      "JAVASCRIPT desde cero | Curso tutorial completo gratis por Sergie Code",
    thumbnail: {
      url: "https://i.ytimg.com/vi/N8Xt5rP_DUo/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "08:17:00",
    url: "https://www.youtube.com/watch?v=N8Xt5rP_DUo",
  },
  {
    id: "x5trGVMKTdY",
    tituloCanal: "CS50",
    titulo: "CS50W - Lecture 5 - JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/x5trGVMKTdY/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "01:51:26",
    url: "https://www.youtube.com/watch?v=x5trGVMKTdY",
  },
  {
    id: "W46pI8haUso",
    tituloCanal: "RoadsideCoder",
    titulo:
      "Reverse a String - Javascript DSA Interview Question #javascript #DSA #javascriptinterview",
    thumbnail: {
      url: "https://i.ytimg.com/vi/W46pI8haUso/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=W46pI8haUso",
  },
  {
    id: "ABPCtQyp7lI",
    tituloCanal: "Bitfumes",
    titulo: "JavaScript - What is hoisting #javascript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/ABPCtQyp7lI/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:51",
    url: "https://www.youtube.com/watch?v=ABPCtQyp7lI",
  },
  {
    id: "ZvbzSrg0afE",
    tituloCanal: "Akshay Saini",
    titulo:
      "How JavaScript Works 🔥& Execution Context | Namaste JavaScript Ep.1",
    thumbnail: {
      url: "https://i.ytimg.com/vi/ZvbzSrg0afE/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:04:58",
    url: "https://www.youtube.com/watch?v=ZvbzSrg0afE",
  },
  {
    id: "z95mZVUcJ-E",
    tituloCanal: "Soy Dalto",
    titulo: "Curso de JAVASCRIPT desde CERO (Completo) - Nivel JUNIOR",
    thumbnail: {
      url: "https://i.ytimg.com/vi/z95mZVUcJ-E/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "10:00:41",
    url: "https://www.youtube.com/watch?v=z95mZVUcJ-E",
  },
  {
    id: "Jv2uxzhPFl4",
    tituloCanal: "Fireship",
    titulo: "Test-Driven Development // Fun TDD Introduction with JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Jv2uxzhPFl4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:12:55",
    url: "https://www.youtube.com/watch?v=Jv2uxzhPFl4",
  },
  {
    id: "utMns8HOFB4",
    tituloCanal: "Creative Tim Tutorials",
    titulo: "9 JavaScript projects for web developers to start doing now!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/utMns8HOFB4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:55",
    url: "https://www.youtube.com/watch?v=utMns8HOFB4",
  },
  {
    id: "cjCzTBp_Bq0",
    tituloCanal: "Sheryians Coding School",
    titulo:
      "9/100 Tricks: HTML CSS JS Animation and Effects #htmlcss #webdevelopment #frontend #coding",
    thumbnail: {
      url: "https://i.ytimg.com/vi/cjCzTBp_Bq0/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=cjCzTBp_Bq0",
  },
  {
    id: "8IHhvkaVqVE",
    tituloCanal: "Beyond Fireship",
    titulo: "Does Deno 2 really uncomplicate JavaScript?",
    thumbnail: {
      url: "https://i.ytimg.com/vi/8IHhvkaVqVE/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:08:55",
    url: "https://www.youtube.com/watch?v=8IHhvkaVqVE",
  },
  {
    id: "Q9fwkpxr3Dw",
    tituloCanal: "Victor Robles WEB",
    titulo: "Aprende JavaScript en 15 Minutos 📒",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Q9fwkpxr3Dw/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:19:06",
    url: "https://www.youtube.com/watch?v=Q9fwkpxr3Dw",
  },
  {
    id: "L__fBIqTUIA",
    tituloCanal: "EDteam",
    titulo: "¿Por qué no basta JavaScript para el frontend?",
    thumbnail: {
      url: "https://i.ytimg.com/vi/L__fBIqTUIA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=L__fBIqTUIA",
  },
  {
    id: "EfAl9bwzVZk",
    tituloCanal: "Dave Gray",
    titulo:
      "JavaScript Full Course for Beginners | Complete All-in-One Tutorial | 8 Hours",
    thumbnail: {
      url: "https://i.ytimg.com/vi/EfAl9bwzVZk/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "07:54:33",
    url: "https://www.youtube.com/watch?v=EfAl9bwzVZk",
  },
  {
    id: "-tee_eW-niQ",
    tituloCanal: "Mehul - Codedamn",
    titulo: "JavaScript Explained in 60 Seconds ⚡️",
    thumbnail: {
      url: "https://i.ytimg.com/vi/-tee_eW-niQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=-tee_eW-niQ",
  },
  {
    id: "jZUHZDXmQ_A",
    tituloCanal: "Web Dev Simplified",
    titulo: "How To Easily Format Dates In JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/jZUHZDXmQ_A/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=jZUHZDXmQ_A",
  },
  {
    id: "OmmJBfcMJA8",
    tituloCanal: "Curso em Vídeo",
    titulo: "Criando o seu primeiro script - Curso JavaScript #04",
    thumbnail: {
      url: "https://i.ytimg.com/vi/OmmJBfcMJA8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:24:15",
    url: "https://www.youtube.com/watch?v=OmmJBfcMJA8",
  },
  {
    id: "7Nox7zGwDjg",
    tituloCanal: "ProCode",
    titulo:
      "Tricky Javascript Interview Questions 03 #shorts #shortvideo #shortsfeed #shortsvideos",
    thumbnail: {
      url: "https://i.ytimg.com/vi/7Nox7zGwDjg/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=7Nox7zGwDjg",
  },
  {
    id: "xcydoidzuGQ",
    tituloCanal: "Gian's Tech",
    titulo:
      "TUTTO JavaScript in 30 MINUTI - Corso Completo PROGRAMMAZIONE FACILE partendo da zero",
    thumbnail: {
      url: "https://i.ytimg.com/vi/xcydoidzuGQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:29:25",
    url: "https://www.youtube.com/watch?v=xcydoidzuGQ",
  },
  {
    id: "2Ji-clqUYnA",
    tituloCanal: "Coding Addict",
    titulo: "Javascript Fundamentals",
    thumbnail: {
      url: "https://i.ytimg.com/vi/2Ji-clqUYnA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "10:22:54",
    url: "https://www.youtube.com/watch?v=2Ji-clqUYnA",
  },
  {
    id: "3xYd9fJ_0Z8",
    tituloCanal: "Kevin Powell",
    titulo: "JavaScript Promises Crash Course",
    thumbnail: {
      url: "https://i.ytimg.com/vi/3xYd9fJ_0Z8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:24:03",
    url: "https://www.youtube.com/watch?v=3xYd9fJ_0Z8",
  },
  {
    id: "uh4gG7LbDPQ",
    tituloCanal: "Codecademy",
    titulo: "Learn JavaScript: Tutorial for Beginners (Part 1)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/uh4gG7LbDPQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:55:35",
    url: "https://www.youtube.com/watch?v=uh4gG7LbDPQ",
  },
  {
    id: "cYNVVspXUdA",
    tituloCanal: "Internet Made Coder",
    titulo: "How I Would Learn Javascript FAST in 2023 (from zero)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/cYNVVspXUdA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:08:09",
    url: "https://www.youtube.com/watch?v=cYNVVspXUdA",
  },
  {
    id: "OJgu_KCCUSY",
    tituloCanal: "Curso em Vídeo",
    titulo: "Tratamento de dados - Curso JavaScript #06",
    thumbnail: {
      url: "https://i.ytimg.com/vi/OJgu_KCCUSY/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:39:16",
    url: "https://www.youtube.com/watch?v=OJgu_KCCUSY",
  },
  {
    id: "NKRpB0pU3vI",
    tituloCanal: "Mago Acadêmico",
    titulo:
      "O Código Javascript Mais Bizarro de Todos! #javascript #programação",
    thumbnail: {
      url: "https://i.ytimg.com/vi/NKRpB0pU3vI/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:50",
    url: "https://www.youtube.com/watch?v=NKRpB0pU3vI",
  },
  {
    id: "HFaxylC7bUc",
    tituloCanal: "Bro Code",
    titulo: "JavaScript FUNCTIONS are easy! 📞",
    thumbnail: {
      url: "https://i.ytimg.com/vi/HFaxylC7bUc/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:12:14",
    url: "https://www.youtube.com/watch?v=HFaxylC7bUc",
  },
  {
    id: "YYWEKjPbRME",
    tituloCanal: "Tech With Tim",
    titulo: "Tutorial: Ever written code like this?",
    thumbnail: {
      url: "https://i.ytimg.com/vi/YYWEKjPbRME/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:58",
    url: "https://www.youtube.com/watch?v=YYWEKjPbRME",
  },
  {
    id: "l_pIZt1a0Og",
    tituloCanal: "JovemScript",
    titulo: "Porque JAVASCRIPT é a PIOR LINGUAGEM DE PROGRAMAÇÃO?",
    thumbnail: {
      url: "https://i.ytimg.com/vi/l_pIZt1a0Og/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:06:19",
    url: "https://www.youtube.com/watch?v=l_pIZt1a0Og",
  },
  {
    id: "NfvtQ2p5QG4",
    tituloCanal: "JavaScript King",
    titulo:
      "HTML CSS JS projects (Beginner): 30 projects using HTML CSS and JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/NfvtQ2p5QG4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "11:59:34",
    url: "https://www.youtube.com/watch?v=NfvtQ2p5QG4",
  },
  {
    id: "QgLedHq1tiI",
    tituloCanal: "ezsNippet",
    titulo:
      "How to be a developer. #coding #programming #webdevelopment #javascript @CodeWithHarry",
    thumbnail: {
      url: "https://i.ytimg.com/vi/QgLedHq1tiI/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:30",
    url: "https://www.youtube.com/watch?v=QgLedHq1tiI",
  },
  {
    id: "qLeziONDVLg",
    tituloCanal: "James Q Quick",
    titulo: "5 MUST HAVE VS Code Extensions for JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/qLeziONDVLg/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:59",
    url: "https://www.youtube.com/watch?v=qLeziONDVLg",
  },
  {
    id: "onCHSujPlfg",
    tituloCanal: "ThePrimeTime",
    titulo: "JavaScript Is Becoming 2 Languages?? FROM TC39",
    thumbnail: {
      url: "https://i.ytimg.com/vi/onCHSujPlfg/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:30:01",
    url: "https://www.youtube.com/watch?v=onCHSujPlfg",
  },
  {
    id: "kZMwrXyxQYE",
    tituloCanal: "Tech With Tim",
    titulo: "Learn JavaScript With These 5 Projects",
    thumbnail: {
      url: "https://i.ytimg.com/vi/kZMwrXyxQYE/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "02:48:51",
    url: "https://www.youtube.com/watch?v=kZMwrXyxQYE",
  },
  {
    id: "kMiH18nwEr8",
    tituloCanal: "Victor Lima - Ciência da Computação",
    titulo: "PHP É uma Linguagem Engraçada 🤡 #shorts #php #javascript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/kMiH18nwEr8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:53",
    url: "https://www.youtube.com/watch?v=kMiH18nwEr8",
  },
  {
    id: "J2q0x70YDPk",
    tituloCanal: "Education 4u",
    titulo: "Javascript | Introduction | Web Technology | Lec-24 | Bhanu Priya",
    thumbnail: {
      url: "https://i.ytimg.com/vi/J2q0x70YDPk/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:06:08",
    url: "https://www.youtube.com/watch?v=J2q0x70YDPk",
  },
  {
    id: "VwF6y91PCH0",
    tituloCanal: "Platzi",
    titulo: "Cuánto durará el reino de JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/VwF6y91PCH0/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:17:57",
    url: "https://www.youtube.com/watch?v=VwF6y91PCH0",
  },
  {
    id: "wWnBB-mZIvY",
    tituloCanal: "Curso em Vídeo",
    titulo: "Eventos DOM - Curso JavaScript #10",
    thumbnail: {
      url: "https://i.ytimg.com/vi/wWnBB-mZIvY/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:28:54",
    url: "https://www.youtube.com/watch?v=wWnBB-mZIvY",
  },
  {
    id: "jt41xX_SMtA",
    tituloCanal: "Programming with Mosh",
    titulo: "Think JavaScript = Job? WRONG!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/jt41xX_SMtA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:59",
    url: "https://www.youtube.com/watch?v=jt41xX_SMtA",
  },
  {
    id: "QFRXnyd4cWw",
    tituloCanal: "Education 4u",
    titulo: "javascript tutorial for beginners | bhanu priya",
    thumbnail: {
      url: "https://i.ytimg.com/vi/QFRXnyd4cWw/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:07:37",
    url: "https://www.youtube.com/watch?v=QFRXnyd4cWw",
  },
  {
    id: "DAxKQIG4T2Y",
    tituloCanal: "CodeWithHarry",
    titulo: "Python vs JavaScript | What to Choose? | ft. Toolify.ai",
    thumbnail: {
      url: "https://i.ytimg.com/vi/DAxKQIG4T2Y/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:09:23",
    url: "https://www.youtube.com/watch?v=DAxKQIG4T2Y",
  },
  {
    id: "m4j9XMXDEAk",
    tituloCanal: "Codecademy",
    titulo:
      "Should you learn #Python or #JavaScript first? It depends on what you want to build.",
    thumbnail: {
      url: "https://i.ytimg.com/vi/m4j9XMXDEAk/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=m4j9XMXDEAk",
  },
  {
    id: "rKiTp5xUjfs",
    tituloCanal: "Rocketseat",
    titulo: "O Estado do Mercado JavaScript #javascript #comunidadedev",
    thumbnail: {
      url: "https://i.ytimg.com/vi/rKiTp5xUjfs/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:01",
    url: "https://www.youtube.com/watch?v=rKiTp5xUjfs",
  },
  {
    id: "alZnDow5czQ",
    tituloCanal: "Tiger Codes",
    titulo: "Top 5 Motivos Para Você Aprender JavaScript em 2023",
    thumbnail: {
      url: "https://i.ytimg.com/vi/alZnDow5czQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=alZnDow5czQ",
  },
  {
    id: "6-dHkHgP2LE",
    tituloCanal: "ThePrimeTime",
    titulo: "STOP Using Classes In JavaScript | Prime Reacts",
    thumbnail: {
      url: "https://i.ytimg.com/vi/6-dHkHgP2LE/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:14:02",
    url: "https://www.youtube.com/watch?v=6-dHkHgP2LE",
  },
  {
    id: "Zq5fmkH0T78",
    tituloCanal: "JavaScript Mastery",
    titulo:
      "Next.js 15 Crash Course | Build and Deploy a Production-Ready Full Stack App",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Zq5fmkH0T78/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "05:23:11",
    url: "https://www.youtube.com/watch?v=Zq5fmkH0T78",
  },
  {
    id: "PD1TPb9kJ2Y",
    tituloCanal: "PitoneProgrammatore",
    titulo:
      "Javascript TUTORIAL ITA - Imparalo SUBITO ! Corso RAPIDO per principianti in ITALIANO [2020]",
    thumbnail: {
      url: "https://i.ytimg.com/vi/PD1TPb9kJ2Y/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:10:09",
    url: "https://www.youtube.com/watch?v=PD1TPb9kJ2Y",
  },
  {
    id: "Vbabsye7mWo",
    tituloCanal: "Curso em Vídeo",
    titulo: "Variáveis e Tipos Primitivos - Curso JavaScript #05",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Vbabsye7mWo/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:31:41",
    url: "https://www.youtube.com/watch?v=Vbabsye7mWo",
  },
  {
    id: "UOXrvCIvwuo",
    tituloCanal: "Neeraj Walia",
    titulo:
      "Html css js is not enough.#coding #programming #html #css #javascript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/UOXrvCIvwuo/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=UOXrvCIvwuo",
  },
  {
    id: "OEQpRTXfxoo",
    tituloCanal: "Interview Happy",
    titulo: "Top 25 JavaScript Interview Questions for Beginners",
    thumbnail: {
      url: "https://i.ytimg.com/vi/OEQpRTXfxoo/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:50:26",
    url: "https://www.youtube.com/watch?v=OEQpRTXfxoo",
  },
  {
    id: "8zKuNo4ay8E",
    tituloCanal: "Akshay Saini",
    titulo:
      "Asynchronous JavaScript & EVENT LOOP from scratch 🔥 | Namaste JavaScript Ep.15",
    thumbnail: {
      url: "https://i.ytimg.com/vi/8zKuNo4ay8E/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:41:45",
    url: "https://www.youtube.com/watch?v=8zKuNo4ay8E",
  },
  {
    id: "gPKzwAORly8",
    tituloCanal: "Piyush Garg",
    titulo: "JavaScript Global Execution Context Explained!",
    thumbnail: {
      url: "https://i.ytimg.com/vi/gPKzwAORly8/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:27:25",
    url: "https://www.youtube.com/watch?v=gPKzwAORly8",
  },
  {
    id: "cGgLHJGyS34",
    tituloCanal: "GreatStack",
    titulo: "How To Make A Calculator Using HTML CSS And JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/cGgLHJGyS34/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:19:01",
    url: "https://www.youtube.com/watch?v=cGgLHJGyS34",
  },
  {
    id: "KWntxkf25nA",
    tituloCanal: "Attekita Dev",
    titulo: "Como aprender JAVASCRIPT, para iniciantes! 👩🏻‍💻",
    thumbnail: {
      url: "https://i.ytimg.com/vi/KWntxkf25nA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:11:08",
    url: "https://www.youtube.com/watch?v=KWntxkf25nA",
  },
  {
    id: "yymyLXPbP1Y",
    tituloCanal: "DIVINE CLASSES AN INSTITUTION Of EDUCATION.",
    titulo:
      "How to become a Senior developer.. ♥️ 😂 #programming #javascript #python #coding #developer #coder .",
    thumbnail: {
      url: "https://i.ytimg.com/vi/yymyLXPbP1Y/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:18",
    url: "https://www.youtube.com/watch?v=yymyLXPbP1Y",
  },
  {
    id: "nAFghpbhAJQ",
    tituloCanal: "midudev",
    titulo: "Comunica pestañas en JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/nAFghpbhAJQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:44",
    url: "https://www.youtube.com/watch?v=nAFghpbhAJQ",
  },
  {
    id: "RTfMHMQp2e4",
    tituloCanal: "DevClub | Programação",
    titulo:
      "🔴 APRENDA FUNÇÕES EM JAVASCRIPT EM ALGUNS MINUTOS - Curso de JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/RTfMHMQp2e4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:22:30",
    url: "https://www.youtube.com/watch?v=RTfMHMQp2e4",
  },
  {
    id: "BP63NhITvao",
    tituloCanal: "Curso em Vídeo",
    titulo: "Operadores (Parte 2) - Curso JavaScript #08",
    thumbnail: {
      url: "https://i.ytimg.com/vi/BP63NhITvao/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:24:26",
    url: "https://www.youtube.com/watch?v=BP63NhITvao",
  },
  {
    id: "Fm8Fc9TV88k",
    tituloCanal: "Learning Axis",
    titulo: "Floating Bubbles Animation | HTML CSS JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/Fm8Fc9TV88k/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=Fm8Fc9TV88k",
  },
  {
    id: "R9I85RhI7Cg",
    tituloCanal: "Codevolution",
    titulo: "Advanced JavaScript Crash Course",
    thumbnail: {
      url: "https://i.ytimg.com/vi/R9I85RhI7Cg/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "01:04:05",
    url: "https://www.youtube.com/watch?v=R9I85RhI7Cg",
  },
  {
    id: "_GTMOmRrqkU",
    tituloCanal: "devdojo",
    titulo: "HTML, CSS, and Javascript in 30 minutes",
    thumbnail: {
      url: "https://i.ytimg.com/vi/_GTMOmRrqkU/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:31:49",
    url: "https://www.youtube.com/watch?v=_GTMOmRrqkU",
  },
  {
    id: "8aGhZQkoFbQ",
    tituloCanal: "JSConf",
    titulo:
      "What the heck is the event loop anyway? | Philip Roberts | JSConf EU",
    thumbnail: {
      url: "https://i.ytimg.com/vi/8aGhZQkoFbQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:26:53",
    url: "https://www.youtube.com/watch?v=8aGhZQkoFbQ",
  },
  {
    id: "xI0yBzTsqsI",
    tituloCanal: "Conner Ardman",
    titulo:
      "Why JavaScript Classes Are Actually Functions | Prototypal Inheritance Explained",
    thumbnail: {
      url: "https://i.ytimg.com/vi/xI0yBzTsqsI/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=xI0yBzTsqsI",
  },
  {
    id: "EFDYcj_6EFs",
    tituloCanal: "Stefan Mischook",
    titulo: "Learning JavaScript Frameworks in 2024",
    thumbnail: {
      url: "https://i.ytimg.com/vi/EFDYcj_6EFs/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:23:07",
    url: "https://www.youtube.com/watch?v=EFDYcj_6EFs",
  },
  {
    id: "iBbBPkVhgNQ",
    tituloCanal: "ColorCode",
    titulo:
      "JavaScript Event Loop Explained! 🚀 | How Async Code Works #shorts #coding #javascript #tutorial #js",
    thumbnail: {
      url: "https://i.ytimg.com/vi/iBbBPkVhgNQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:01:00",
    url: "https://www.youtube.com/watch?v=iBbBPkVhgNQ",
  },
  {
    id: "MombnkR3oD4",
    tituloCanal: "Hashtag Programação",
    titulo: "Aprenda JavaScript em 10 min [Iniciantes]",
    thumbnail: {
      url: "https://i.ytimg.com/vi/MombnkR3oD4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:14:43",
    url: "https://www.youtube.com/watch?v=MombnkR3oD4",
  },
  {
    id: "IFZZAaiatcQ",
    tituloCanal: "CodeWithHarry",
    titulo: "JavaScript Arrays | Sigma Web Development Course - Tutorial #63",
    thumbnail: {
      url: "https://i.ytimg.com/vi/IFZZAaiatcQ/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:30:52",
    url: "https://www.youtube.com/watch?v=IFZZAaiatcQ",
  },
  {
    id: "ciz2UaifaNM",
    tituloCanal: "CS50",
    titulo: "CS50x 2024 - Lecture 8 - HTML, CSS, JavaScript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/ciz2UaifaNM/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "02:29:29",
    url: "https://www.youtube.com/watch?v=ciz2UaifaNM",
  },
  {
    id: "aYyZUDFZTrM",
    tituloCanal: "Fireship",
    titulo:
      'JavaScript framework reinvents itself… Did "runes" just ruin Svelte?',
    thumbnail: {
      url: "https://i.ytimg.com/vi/aYyZUDFZTrM/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:04:19",
    url: "https://www.youtube.com/watch?v=aYyZUDFZTrM",
  },
  {
    id: "--VcGI9iPvw",
    tituloCanal: "Akshay Saini",
    titulo: "Top 9 JavaScript topics to know before learning React JS in 2024",
    thumbnail: {
      url: "https://i.ytimg.com/vi/--VcGI9iPvw/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:10:26",
    url: "https://www.youtube.com/watch?v=--VcGI9iPvw",
  },
  {
    id: "jC5v-0USpc4",
    tituloCanal: "Cod3r Cursos",
    titulo: "Quais os 5 Principais Conceitos do JavaScript?",
    thumbnail: {
      url: "https://i.ytimg.com/vi/jC5v-0USpc4/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:34:57",
    url: "https://www.youtube.com/watch?v=jC5v-0USpc4",
  },
  {
    id: "13Jvpp_SjzE",
    tituloCanal: "dcode",
    titulo:
      "SUPER USEFUL JavaScript Console Tool for Developers (Live Expression)  #dcode #javascript",
    thumbnail: {
      url: "https://i.ytimg.com/vi/13Jvpp_SjzE/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "00:00:39",
    url: "https://www.youtube.com/watch?v=13Jvpp_SjzE",
  },
  {
    id: "McKNP3g6VBA",
    tituloCanal: "Programação Web",
    titulo: "Curso Javascript Completo (6 Horas)",
    thumbnail: {
      url: "https://i.ytimg.com/vi/McKNP3g6VBA/default.jpg",
      width: 120,
      height: 90,
    },
    duracao: "06:09:54",
    url: "https://www.youtube.com/watch?v=McKNP3g6VBA",
  },
];
